### ISSUE TITLE
Custom button properties not working

### ISSUE THREAD

**Issue by MicroDroid** [finpo/vue2-recaptcha-invisible#1]
I'm using it like:

```HTML
<g-recaptcha class="btn btn-primary" id="..." :disabled="..."
	data-sitekey="..."
	:data-validate="submit"
	:data-callback="signup">Create account</g-recaptcha>
```

and it renders fancy button of what I've styled with a custom unstyled button right inside, and the disabled property does rather not work:

![image](https://user-images.githubusercontent.com/8523135/27981806-d533367a-639a-11e7-867a-a524ed48b9bc.png)

**Comment by ausir0726** [comment]
@MicroDroid  

please update to 1.1.3

now  you can use `:data-btn-class` bind class and use `:data-btn-disabled` bind disabled prop

`class` prop will apply out-side div class not the button .

thanks.

**Comment by ausir0726** [comment]
You can find example 

here
https://github.com/finpo/vue2-recaptcha-invisible/blob/master/examples/base/src/components/Hello.vue#L10

**Comment by MicroDroid** [comment]
@ausir0726 Thanks a lot for your efforts. During the time I was waiting for the fix, I had actually created my [own invisible recaptcha component](https://github.com/MicroDroid/vue-invisible-recaptcha), given it was modular enough, I just published it to NPM and GitHub. :)
