### ISSUE TITLE
Error: Invalid ReCAPTCHA client id: 0

### ISSUE THREAD

**Issue by zakst** [finpo/vue2-recaptcha-invisible#2]
Hi, 

I get the error `Error: Invalid ReCAPTCHA client id: 0` at random times, and it only goes away after a random number of page refreshes. 

Any ideas as to why that happens, the solutions online of removing `render=explicit` or `resetting` `grecaptha` do not work.

--Edit--
Seems to occur more often in `Firefox`

Cheers

**Comment by ausir0726** [comment]
thanks,

I will try to reduce this error .
In my production case , don't happen this error.
If you can provide a simple project reduce this problem will be helpful .

thanks.

**Comment by zakst** [comment]
Sorry for the late reply. Tried to create an app showing the error but no luck. Till just now the error appeared again, as attached. Once i refreshed the page everything worked fine. 

There are no other errors in the `console` . I will still try to demonstrate it better once i figure out a pattern.

![vuerecaptcha](https://user-images.githubusercontent.com/12071456/29491165-3282bf86-8596-11e7-83bf-bb39dad755ab.png)

**Comment by ausir0726** [comment]
my guess , 

seems like it mount google recaptcha js file more than once .
maybe I can try remove older js file in head , then re-mount js file .

thanks.

**Comment by ausir0726** [comment]
try 1.1.8 , maybe can fix this issue.
thanks.
