### ISSUE TITLE
Not compatible with SSR

### ISSUE THREAD

**Issue by IlyaSemenov** [finpo/vue2-recaptcha-invisible#8]
The compiled version in `dist/` uses the hardcoded reference to `window`. In Vue SSR (Nuxt or Ream), it crashes:

```
✖ error ReferenceError: window is not defined
  at Object.<anonymous> (/Users/semenov/xxx/node_modules/@finpo/vue2-recaptcha-invisible/dist/index.js:1:325)
```

Importing the actual SFC file as `import Recaptcha from '@finpo/vue2-recaptcha-invisible/src/reCaptchaComponent.vue'` works fine, but transpiling from `node_modules` should generally be avoided. Also, it's hard to setup properly through the entire stack, e.g. in my case I'm stuck with the linter not being able to recognize that I import a SFC from `node_modules`.

**Comment by ausir0726** [comment]
@IlyaSemenov  Thanks.

Seems like last I update webpack 4, It breaks my dist build.
I will fix it ASAP.

**Comment by IlyaSemenov** [comment]
By the way, did you consider rollup instead of webpack? It seems to be a better fit for creating distributable modules (I have used both).

**Comment by ausir0726** [comment]
umm... 

I never used rollup. I don't know.
maybe I will understand it when I available.

**Comment by ausir0726** [comment]
@IlyaSemenov 

Seems like it's webpack 4 umd mode have some issue will break this project.
so, I restore to webpack 2.3.

thank for your report, I am trying to rollup package.

I released 1.1.9 fixed this bug.

**Comment by ausir0726** [comment]
1.2.0 refactor to rollup.
support sfc, esm, umd, unpkg format.

**Comment by IlyaSemenov** [comment]
I confirm that it works in SSR. Thanks!
